.TH dtc-xen_domUconf_standard 8
.SH NAME
dtc-xen_domUconf_standard \- configure a debian VPS for using network
.SH SYNOPSIS

.B dtc-xen_domUconf_standard
.I VPS_PATH
.I VPSHOSTNAME
.I NODE_DOMAIN_NAME
.I KERNELNAME
.I IPADDR

.SH DESCRIPTION
.B dtc-xen_domUconf_standard
This shell script is a part of the dtc-xen package that is to be used by the
dtc panel to manage a Xen VPS server.

When doing it's VPS install, dtc_reinstall_os will call a script to do the setup
of the standard things like hostname, /etc/hosts, etc. dtc-xen_domUconf_standard
does the job when the VPS type is more or less standard, this can be overriden
whenever needed for other types of OS.

This does NOT include the setup of the network address(es) or the bootstrap of
the operating system. Such tasks are performed elsewhere.

See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
