.TH dtc-xen_domUconf_network_debian 8
.SH NAME
dtc-xen_domUconf_network_debian \- configure a debian VPS for using network
.SH SYNOPSIS

.B dtc-xen_domUconf_network_debian
.I VPS_PATH
.I IP_ADDR
.I NETMASK
.I NETWORK
.I BROADCAST
.I GATEWAY

.SH DESCRIPTION
.B dtc-xen_domUconf_network_debian
This shell script is a part of the dtc-xen package that is to be used by the
dtc panel to manage a Xen VPS server.

When doing it's VPS install, dtc_reinstall_os will call a script to do the setup
of the network. dtc-xen_domUconf_network_debian does the job when the VPS type
is Debian (that is: works also for Ubuntu based VPS).

See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
