.TH dtc-soap-server 8
.SH NAME
dtc-soap-server \- This is a SOAP server running over HTTPS with Auth to remotly start/stop/reinstall/fsck a VPS under Xen
.SH SYNOPSIS
.B dtc-soap-server [\fI-D\fR] [\fI-v\fR]

.SH DESCRIPTION
.B dtc-soap-server
This soap server script is a part of the dtc-xen
package that is to be used by the DTC control panel
to manage a Xen VPS server.

It will bind a soap server with auth using SSL on the
port defined in /etc/dtc-xen/soap.conf. It's auth users are
also defined in the /etc/dtc-xen/htpasswd, use the htpasswd
utility from apache / apache2 to edit it.

If you're using this server in CentOS, you can replace
the SSL certificate this program uses by replacing
the files named dtc-xen.* inside /etc/pki/tls.  Check the
README.RPM file distributed with the package for expedited
instructions on how to set up an administrative password.

The -D command line option daemonizes the server.
The -v command line option elevates logging level to debug.

.SH "VERSION"
This documentation describes
.B dtc-soap-server

See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
