.TH dtc-soap-server 8
.SH NAME
dtc-soap-server \- This is a SOAP server running over HTTPS with Auth to remotly start/stop/reinstall/fsck a VPS under Xen
.SH SYNOPSIS
.B dtc-soap-server

.SH DESCRIPTION
.B dtc-soap-server
This soap server script is a part of the dtc-xen
package that is to be used by the dtc panel
to manage a Xen VPS server.

It will bind a soap server with auth using SSL on the
port defined in /etc/dtc-xen. It's auth users are also defined
in the /etc/dtc-xen/htpasswd, use the htpasswd utility from
apache / apache2 to edit it.

.SH "VERSION"
This documentation describes
.B dtc-soap-server

See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
