.TH dtc_reinstall_os 8
.SH NAME
dtc_reinstall_os \- reinstall an operating system in a VM
.SH SYNOPSIS
.B dtc_reinstall_os
[
.I -v
]
[ OPTIONS ]
.I -vpsid <ID>
.I -ram <RAM size MB>
.I -nic <ip>[,<netmask>[,<broadcast>]]
.I -pass <root-password>
.I -os <operating-system>
.I [ -gw <default-gateway> ]
]

.SH DESCRIPTION
.B dtc_reinstall_os
.IP
This shell script is a part of the dtc-xen package that is to be used by the
dtc panel to manage a Xen VPS server.

.SH DESCRIPTION
.LP
.I dtc-reinstall_os
will bootstrap an operating system for you, so you can later use it in a
virtual machine (a VPS). This script will be called by dtc-xen when you order
it to install a VPS through the SOAP server.

.I Additional configuration files
.IP
When doing it's setup, dtc_reinstall_os will copy the file
/etc/dtc-xen/authorized_keys2 into the VPS's /root/.ssh/authorized_keys2 and
/root/.ssh/authorized_key, so the administrator has access to the VPS without
the need of shutting it down. So it's a good idea to copy your shh public key
in /etc/dtc-xen/authorized_keys2. dtc_reinstall_os will also copy
/etc/dtc-xen/motd into the /etc/motd of the VPS (and /etc/motd.tail if a
Debian operating system is installed), and /etc/dtc-xen/bashrc into the
/root/.bashrc.

.SH PARAMETERS
.LP
All parameters described here are mandatory. dtc_reinstall_os will exit if one
of the parameters is missing.

.B -vpsid <ID>
.IP
ID has to be a number between 01 and 99. Each time a new VPS is created, an
associated user xen<ID> will be created on the system, using
/usr/bin/dtc-xen_userconsole so your users can login into the system. When
they login, "xm console xen<ID>" will in fact be their shell, so they can
access the physical console of the VPS using ssh.

.LP
.B -ram <RAM size MB>
.IP
This is the amount of memory in mega bytes that you want to have setup
in the Xen startup file for this virtual machine.

.LP
.B -nic <ip>[,<netmask>[,<broadcast>]]
.IP
This parameter defines the network configuration of the virtual machine,
together with the -gw option (see below). There can be as many -nic option
as you like. If there is more than one, then dtc_reinstall_os will setup
a physical NIC configuration, and as many eth0:X virtual alias as needed.
If the <netmask> or <broadcast> parameter is missing, then the values
will be taken from /etc/dtc-xen/dtc-xen.conf. These variables are called
NETMASK and BROADCAST. Note that each IP address will be added to the
Xen startup configuration file of the virtual machine, so that you can
use the anti-spoof facility of the Xen firewall (highly recommended, if
you are reselling VPS). See Xen documentation on how to activate the
anti-spoof feature of xend.

.LP
.B PASSWORD
is the root password you wish to have setup inside the VPS. Not all operating
system setup will suport it, but it's still a mandatory parameter.

.LP
.B [ DISTRO ]
is an optional parameter that can be debian, centos, gentoo or netbsd.
If ommited it will use debian as default. Note that for centos and gentoo,
you need to have the install files downloaded in /usr/src/gentoo:
.B portage-latest.tar.bz2
and
.B stage3-amd64-2006.1.tar.bz2
(if using amd64 arch) or
.B stage3-x86-2006.1.tar.bz2
(if using i[3456]86 arch).

.LP
.B [ lvm | loopback ]
You can then specify lvm or loopback. Currently the only value the script compares
to is lvm (or anything else), but this might change in the future. If ommited, then
lvm loopback is used.

.SH "OPTION"

If you don't set these options, then they have to be set in /etc/dtc-xen/dtc-xen.conf.

.LP
.B --netmask netmask
.IP
Guest OS netmask to setup.

.LP
.B --network network
.IP
Guest OS network to setup.

.LP
.B --broadcast broadcast
.IP
Guest OS broadcast to setup

.LP
.B --gateway gateway
.IP
Guest OS network gateway to setup

.LP
.B --nameservers dns1,dns2...
.IP
List of DNS servers in the /etc/resolv.conf of the VPS

.LP
.B -v
.IP
Without \-v, dtc_reinstall_os normally
outputs everything in /var/lib/dtc-xen/mnt/XX.stderr and
/var/lib/dtc-xen/mnt/XX.stdout (or wherever you have set the vps mountpoint to be),
to keep a log of the installation. With \-v, the redirection of standard output and
error is not done.

.SH "EXAMPLE"

.B dtc_reinstall_os 16 15360 256 '66.2.45.2 66.2.45.3' debian lvm

This will setup the VM called xen16, build it's startup file in /etc/xen/xen16 with
a vif containing ip=66.2.45.2 66.2.45.3 and 256 MB of RAM, setting-up a debian
stable operating system with 66.2.45.2 setup as eth0 IP address (66.2.45.3 is to
be added later on manually in /etc/network/interfaces later).

.SH "SEE ALSO"

dtc_setup_vps_disk(8), dtc_kill_vps_disk(8)

.SH "VERSION"
This documentation describes
.B dtc_reinstall_os
version 0.3.15.

See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
