.TH vgdisplay_free_size 8
.SH NAME
vgdisplay_free_size \- This script is a part of the SOAP server of dtc-xen running over HTTPS with Auth.
.SH SYNOPSIS
.B vgdisplay_free_size

.SH DESCRIPTION
.B vgdisplay_free_size
This shell script is a part of the dtc-xen
package that is to be used by the dtc panel
to manage a Xen VPS server.

.SH "VERSION"
This documentation describes
.B vgdisplay_free_size
version 0.1.2.
See
.B http://www.gplhost.com/software-dtc-xen.html
for updates.
