#!/bin/sh

# Source debconf library -- we have a Depends line
# to make sure it is there...

action=$1
version=$2

. /usr/share/debconf/confmodule
db_version 2.0

# Todo: use db_subst to get the hostname -fqdn value!
hostname_tested=`hostname -f`
db_subst dtc-xen/conf_soap_hostname default_conf_soap_hostname ${hostname_tested}
db_input high dtc-xen/conf_soap_hostname
db_input low dtc-xen/conf_soap_port
db_input high dtc-xen/conf_soap_login
db_input high dtc-xen/conf_soap_pass
db_input high dtc-xen/conf_node_number
db_input high dtc-xen/conf_debian_repository
db_input high dtc-xen/conf_netmask
db_input high dtc-xen/conf_network
db_input high dtc-xen/conf_broadcast
db_input high dtc-xen/conf_gateway
db_input high dtc-xen/conf_linux_kernel_name
db_input high dtc-xen/conf_lvm_name
db_input high dtc-xen/conf_info_finish_setup
db_go

exit 0;
