#!/bin/sh

set -e

action=$1
version=$2

. /usr/share/debconf/confmodule
db_version 2.0

# Get the values from files if they exist (as the user might have modified them).
if [ -f /etc/dtc-xen/dtc_create_vps.conf.sh ] ; then
	. /etc/dtc-xen/dtc_create_vps.conf.sh
fi
if [ -f /etc/dtc-xen/soap.conf ] ; then
	. /etc/dtc-xen/soap.conf
fi

# Set the debconf values according to what was saved in the config files
if [ -z "${soap_server_port}" ] ; then
	db_set dtc-xen/conf_node_number ${soap_server_port}
fi
if [ -z "${soap_server_dtcxen_user}" ] ; then
	db_set dtc-xen/conf_soap_login ${soap_server_dtcxen_user}
fi
if [ -z "${NODE_DOMAIN_NAME}" ] ; then
	db_set dtc-xen/conf_soap_domain_name ${NODE_DOMAIN_NAME}
fi
if [ -z "${NODE_NUM}" ] ; then
	db_set dtc-xen/conf_node_number ${NODE_NUM}
fi
if [ -z "${NETMASK}" ] ; then
	db_set dtc-xen/conf_netmask ${NETMASK}
fi
if [ -z "${NETWORK}" ] ; then
	db_set dtc-xen/conf_network ${NETWORK}
fi
if [ -z "${BROADCAST}" ] ; then
	db_set dtc-xen/conf_broadcast ${BROADCAST}
fi
if [ -z "${GATEWAY}" ] ; then
	db_set dtc-xen/conf_gateway ${GATEWAY}
fi
if [ -z "${KERNELNAME}" ] ; then
	db_set dtc-xen/conf_linux_kernel_name ${KERNELNAME}
fi
if [ -z "${LVMNAME}" ] ; then
	db_set dtc-xen/conf_lvm_name ${LVMNAME}
fi

db_input low dtc-xen/conf_soap_port || true
db_input high dtc-xen/conf_soap_login || true
db_input high dtc-xen/conf_soap_pass || true
db_input high dtc-xen/conf_soap_domain_name || true
db_input high dtc-xen/conf_node_number || true
db_input high dtc-xen/conf_debian_repository || true
db_input high dtc-xen/conf_netmask || true
db_input high dtc-xen/conf_network || true
db_input high dtc-xen/conf_broadcast || true
db_input high dtc-xen/conf_gateway || true
db_input high dtc-xen/conf_linux_kernel_name || true
db_input high dtc-xen/conf_lvm_name || true
db_input high dtc-xen/conf_info_finish_setup || true
db_go

exit 0;
