#!/bin/bash

#echo "Not start/stop doing for debug purpose now!"
#exit 0

PYTHON=/usr/bin/python
case "$1" in
    start)
        echo -n "Starting python SOAP server: dtc-soap-server.py"
	start-stop-daemon --start --oknodo --pidfile /var/run/dtc-xen-soap-server.pid \
		--exec $PYTHON /usr/sbin/dtc-soap-server.py
        echo "done!"
        ;;
    stop)
    	echo -n "Stoping python SOAP server: dtc-soap-server.py"
    	start-stop-daemon --start --oknodo --pidfile /var/run/dtc-xen-soap-server.pid
        ;;
    restart|reload|force-reload)
    	$0 stop
        $0 start
        ;;
    *)
        echo 'Usage: /etc/init.d/dtc-xen-soap {start|stop|restart|reload}'
        exit 1
esac
exit 0
