#!/bin/bash

### BEGIN INIT INFO
# Provides:          dtc-xen-soap-server
# Required-Start:    $all
# Required-Stop:
# Should-Start:      $local_fs
# Should-Stop:       $local_fs
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Provide a SOAP server facility for managing your Xen VMs
# Description:       dtc-xen is a SOAP server running over HTTPS with auth,
#                    so a web GUI tool can manage, create and destroy your
#                    domU under Xen. This package is to be run in the dom0
#                    of your Xen server. It's written to integrate within DTC
#                    web hosting control panel.
### END INIT INFO

PYTHON=/usr/bin/python
case "$1" in
	start)
		echo -n "Starting python SOAP server: dtc-soap-server "
		start-stop-daemon --start -b --quiet --pidfile /var/run/dtc-xen-soap-server.pid --make-pidfile --exec $PYTHON /usr/sbin/dtc-soap-server
		echo "."
        ;;

	stop)
		echo -n "Stoping python SOAP server: dtc-soap-server "
		start-stop-daemon --stop --oknodo --pidfile /var/run/dtc-xen-soap-server.pid
		echo "."
	;;

	restart|reload|force-reload)
		$0 stop
		sleep 1
		$0 start
	;;

	*)
		echo 'Usage: /etc/init.d/dtc-xen {start|stop|restart|reload}'
		exit 1

esac

exit 0
