#!/bin/bash

MODPROBE=/sbin/modprobe
case "$1" in
        start)
                echo "Adding linux default capabilities module"
                $MODPROBE capability
                echo "done!"
                ;;
        stop)
                ;;
        restart)
                $0 start
                ;;
        reload|force-reload)
                ;;
        *)
                echo "Usage: /etc/init.d/capabilities
{start|stop|restart|reload}"
                exit 1
esac
exit 0


