#!/bin/sh

set -e

. /usr/share/dtc-xen/dtc-xen-parse-param

ETC="${VPS_PATH}/etc"

if [ "${VIRT_TYPE}" = "vz" ] ; then
	ETHNAME_PREFIX=vnet
else
	ETHNAME_PREFIX=eth
fi

if [ ! -z "${NICS}" ] ; then
	echo "auto lo
iface lo inet loopback
" >${ETC}/network/interfaces
	# Configure the eth0
	N=0
	for i in $NICS ; do
		N_IP=`echo ${i} | cut -s -d"," -f1`
		N_MASK=`echo ${i} | cut -s -d"," -f2`
		N_BCAST=`echo ${i} | cut -s -d"," -f3`
		N_NET=`ipcalc -n ${N_IP} ${N_MASK} | grep Network | awk '{print $2}' | cut -d"/" -f1`
		if [ -z "${N_NET}" ] ; then
			N_NET=`ipcalc -n ${N_IP} ${N_MASK} | cut -d"=" -f2`
		fi
		if [ ${N} = 0 ] ; then
			DEVICE="${ETHNAME_PREFIX}0"
		else
			DEVICE="${ETHNAME_PREFIX}0:${N}"
		fi
		echo "auto ${DEVICE}
iface ${DEVICE} inet static
	address ${N_IP}
	netmask ${N_MASK}
	network ${N_NET}
	broadcast ${N_BCAST}" >>${ETC}/network/interfaces
		if [ ${N} = 0 ] ; then
			echo "	gateway ${GATEWAY}" >>${ETC}/network/interfaces
		fi
		echo "" >>${ETC}/network/interfaces
		N=$(( ${N} + 1 ))
	done
fi
# Set the resolv.conf
echo "nameserver "`echo ${DNS} | cut -d"," -f1` > ${ETC}/resolv.conf

if [ -z ""`echo ${DNS} | cut -s -d"," -f2` ] ; then
	echo `echo ${DNS} | cut -s -d"," -f2` >>${ETC}/resolv.conf
fi
