#!/bin/sh

# To be included by each scripts for parsing

NUM_NIC=0
for i in $@ ; do
        case "${1}" in
        "-path")
        	VPS_PATH="${2}"
        	shift
        	shift
        	;;
        "-vpsid")
                VPSNUM="${2}"
                shift
                shift
                ;;
        "-nic")
		PARAM=${2}
                # Manage the nics to give it as parameters to the setup-vps-network script
                if [ "${NUM_NIC}" = 0 ] ; then
                        ALL_IPADDRS=`echo ${PARAM} | cut -d"," -f1`
			FIRST_IP=echo ${PARAM} | cut -s -d"," -f1
                        FW_NICS_CMD="-nic ${PARAM}"
                        NICS=$NICS"
"${PARAM}
                else
                        ALL_IPADDRS="${ALL_IPADDRS} "`echo ${PARAM} | cut -d"," -f1`
                        FW_NICS_CMD="${FW_NICS_CMD} -nic ${PARAM}"
                        NICS=${PARAM}
                fi
                NUM_NIC=$(( ${NUM_NIC} + 1 ))
                shift
                shift
                ;;
	"-gw")
		GATEWAY="$2"
		shift
		shift
		;;
	"--vps-fqdn")
		VPS_FQDN="$2"
		shift
		shift
		;;
	"--vps-domain")
		VPS_DOMAIN="$2"
		shift
		shift
		;;
	"--node-fqdn")
		NODE_FQDN="$2"
		shift
		shift
		;;
	"-dns")
		DNS=${1}
		shift
		shift
		;;
	"--kernel")
		KERNELPATH="$2"
                shift
                shift
                ;;
        "--kernel-release")
                KERNEL_RELEASE=${2}
                shift
                shift
                ;;
	"-kmod-path")
		KMOD_PATH="${2}"
		shift
		shift
		;;
	"--initrd")
		INITRDPATH="${2}"
		shift
		shift
		;;
	esac
done

KERNEL_P="--kernel ${KERNELPATH} --kernel-release ${KERNEL_RELEASE} --kmod-path ${KMOD_PATH} --initrd ${INITRDPATH}"
FW_PARAMS="-vpsid ${VPSNUM} --vps-fqdn ${VPS_FQDN} --vps-domain ${VPS_DOMAIN} --node-fqdn ${NODE_FQDN} ${FW_NICS_CMD} -dns ${DNS} -gw ${GATEWAY} ${KERNEL_P}"
