#!/bin/sh

. /usr/share/dtc-xen/dtc-xen-parse-param

ETC="${VPS_PATH}/etc"

# Configure the eth0
if [ -z "${NICS}" ] ; then
	N=0
	for i in $NICS ; do
		N_IP=`echo ${i} | cut -s -d"," -f1`
		N_MASK=`echo ${i} | cut -s -d"," -f2`
		N_BCAST=`echo ${i} | cut -s -d"," -f3`
		N_NET=`ipcalc -n ${N_IP} ${N_MASK} | grep Network | awk '{print $2}' | cut -d"/" -f1`
		if [ -z "${N_NET}" ] ; then
			N_NET=`ipcalc -n ${N_IP} ${N_MASK} | cut -d"=" -f2`
		fi
		if [ ${N} = 0 ] ; then
			DEVICE="eth0"
		else
			DEVICE="eth0:${N}"
		fi
echo "DEVICE=${DEVICE}
BOOTPROTO=static
BROADCAST=${N_BCAST}
IPADDR=${N_IP}
NETMASK=${N_MASK}
NETWORK=${N_NET}
ONBOOT=yes
" >${ETC}/sysconfig/network-scripts/ifcfg-${DEVICE}
	done
	# Set the gateway file
	echo "NETWORKING=yes
HOSTNAME=mx.xen${VPSNUM}.${NODE_FQDN}
GATEWAY=${GATEWAY}
" >${ETC}/sysconfig/network
fi

# Set the resolv.conf
echo "nameserver "`echo ${DNS} | cut -d"," -f1` > ${ETC}/resolv.conf

if [ -z ""`echo ${DNS} | cut -s -d"," -f2` ] ; then
	echo `echo ${DNS} | cut -s -d"," -f2` >>${ETC}/resolv.conf
fi
