#!/bin/sh

if [ $# -lt 1 ]; then 
	echo "Usage: $0 <xen id> [lvm/vbd]"
	exit
fi

# Things that often change

# Source the configuration in the config file!
if [ -f /etc/dtc-xen/dtc-xen.conf ] ; then
	. /etc/dtc-xen/dtc-xen.conf
fi

# Figure out the VPS mount point
if [ -n "$provisioning_mount_point" ]
then
	VPSGLOBPATH="$provisioning_mount_point"
else
	VPSGLOBPATH="$VPS_MOUNTPOINT"
fi

# Things that most of then time don't change
VPSNUM=$1
VPSNAME=xen${VPSNUM}
VPSHOSTNAME=xen${NODE_NUM}${VPSNUM}
IMAGE_TYPE=$2

if [ -z "$IMAGE_TYPE" ] ; then IMAGE_TYPE=lvm ; fi

# Figure out the LVM name from dtc-xen.conf
if [ "$IMAGE_TYPE" = "lvm" ] ; then
	LVMNAME=`dtc-xen-volgroup`
	[ -z "$LVMNAME" ] && {
		echo "Could not determine volume group from which to provision the volume" 1>&2
		echo "You might want to set provisioning_volgroup in dtc-xen.conf" 1>&2
		exit 78
	}
fi

# redirect stdout and stderr to log files, so we can see what happened during install

echo "Redirecting standard output to $VPSGLOBPATH/$VPSNUM.stdout..."
echo "Redirecting standard error to $VPSGLOBPATH/$VPSNUM.stderr..."
if [ -e $VPSGLOBPATH/$VPSNUM.setuplvm.stdout ]; then
        mv $VPSGLOBPATH/$VPSNUM.setuplvm.stdout $VPSGLOBPATH/$VPSNUM.setuplvm.stdout.old
fi
if [ -e $VPSGLOBPATH/$VPSNUM.setuplvm.stderr ]; then
        mv $VPSGLOBPATH/$VPSNUM.setuplvm.stderr $VPSGLOBPATH/$VPSNUM.setuplvm.stderr.old
fi

exec 1>$VPSGLOBPATH/$VPSNUM.setuplvm.stdout
exec 2>$VPSGLOBPATH/$VPSNUM.setuplvm.stderr

if [ -x /sbin/lvcreate -a /sbin/lvremove ] ; then
	LVCREATE=/sbin/lvcreate
	LVREMOVE=/sbin/lvremove
else
	if [ -x /usr/sbin/lvcreate -a /usr/sbin/lvremove ] ; then
		LVCREATE=/usr/sbin/lvcreate
		LVREMOVE=/usr/sbin/lvremove
	else
		echo "Could not find lvcreate and lvremove binaries!" > /dev/stderr
		exit 1
	fi
fi

echo "Seleted ${VPSNAME}";
echo "Destroying disks..."

if [ ""$IMAGE_TYPE = "lvm" ]; then
	# Remove existing partitions if they existed
	if [ -L /dev/${LVMNAME}/${VPSNAME} ] ; then
		$LVREMOVE -f /dev/${LVMNAME}/${VPSNAME}
	fi
	if [ -L /dev/${LVMNAME}/${VPSNAME}swap ] ; then
		$LVREMOVE -f /dev/${LVMNAME}/${VPSNAME}swap
	fi
else
	if [ -e ${VPSGLOBPATH}/${VPSNAME}.img ]; then
		umount ${VPSGLOBPATH}/${VPSNAME}.img
		rm ${VPSGLOBPATH}/${VPSNAME}.img
	fi
	if [ -e ${VPSGLOBPATH}/${VPSNAME}.swap.img ]; then
		umount ${VPSGLOBPATH}/${VPSNAME}.swap.img
		rm ${VPSGLOBPATH}/${VPSNAME}.swap.img
	fi
fi

# Remove the auto start file
if [ -f /etc/xen/auto/${VPSNAME} ] ; then
	rm /etc/xen/auto/${VPSNAME}
fi
